# Generated by Django 6.1 on 2026-08-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NazariiKolesnikovPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name="Nazarii Kolesnikov's Portfolio")),
                ('image', models.ImageField(upload_to='portfolio_images/', verbose_name='Portfolio Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
    ]
